#pragma kernel MAIN

AppendStructuredBuffer<float4> gPosition;

uniform int gCount;

uniform float gSpacing;
uniform int gWidth;

[numthreads(64, 1, 1)]
void MAIN(uint3 id : SV_DispatchThreadID)
{
    uint tID = id.x;

    if ((int)tID >= gCount) return;

    uint width = gWidth;
    float spacing = gSpacing;

    gPosition.Append(float4((tID % width) * spacing, (tID / width) * spacing, 0, 0));
}
